/* Licensed under MIT 2025-2026. */
package edu.kit.kastel.mcse.ardoco.tlr.models.connectors.generators.antlr.extraction;

import java.io.IOException;
import java.nio.file.Path;
import java.util.List;

import org.antlr.v4.runtime.CommonTokenStream;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import edu.kit.kastel.mcse.ardoco.tlr.models.connectors.generators.antlr.management.ElementStorageRegistry;

/**
 * Is responsible for extracting elements from an directory. The extracted
 * elements are then stored in an ElementStorageRegistry.
 * The extraction process is implemented by the implementing class. The
 * extraction process is done by building a token stream from
 * a file via ANTLR and extracting the elements from the token stream.
 * After the extraction of structural elements, the CommentExtractor is called
 * to extract comments from the file and added to the
 * ElementStorageRegistry.
 */
public abstract class ElementExtractor {
    protected CommentExtractor commentExtractor;
    protected final Logger logger = LoggerFactory.getLogger(ElementExtractor.class);

    public abstract ElementStorageRegistry getElements();

    /**
     * Extracts elements from the given directory
     * 
     * @param directoryPath, the path of the directory as string
     */
    public void extract(String directoryPath) {
        Path root = Path.of(directoryPath).toAbsolutePath().normalize();
        List<Path> files = getFiles(directoryPath);
        for (Path file : files) {
            Path absolute = file.toAbsolutePath().normalize();
            Path relative = root.relativize(absolute);
            extractContent(absolute, relative);
        }
    }

    /**
     * Extracts the content of the given file
     *
     * @param absoluteFile, the absolute path used to read the file
     * @param relativeFile, the path relative to the project root used as source name
     */
    protected void extractContent(Path absoluteFile, Path relativeFile) {
        CommonTokenStream tokens;
        try {
            tokens = buildTokens(absoluteFile, relativeFile);
        } catch (IOException e) {
            logger.error("I/O operation failed", e);
            return;
        }
        extractElements(tokens);
        extractComments(relativeFile, tokens);
    }

    /**
     * Extracts comments from the given file, using the given token stream
     *
     * @param file,   the path of the file
     * @param tokens, the token stream generated by the ANTLR parser
     */
    protected void extractComments(Path file, CommonTokenStream tokens) {
        String path = file.toString();
        commentExtractor.extract(path, tokens);
    }

    /**
     * Returns a list of files in the given directory
     *
     * @param directoryPath the path of the directory as String
     * @return a list of files in the directory as Path objects
     */
    protected abstract List<Path> getFiles(String directoryPath);

    /**
     * Builds a token stream from the given file
     *
     * @param absoluteFile, the absolute path used to read the file from disk
     * @param relativeFile, the relative path set as the ANTLR source name
     * @return the token stream generated by the ANTLR parser
     * @throws IOException if the file cannot be read
     */
    protected abstract CommonTokenStream buildTokens(Path absoluteFile, Path relativeFile) throws IOException;

    /**
     * Extracts structural elements from the given token stream
     * 
     * @param tokens, the token stream generated by the ANTLR parser
     */
    protected abstract void extractElements(CommonTokenStream tokens);
}
