<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.github.ardoco.core</groupId>
    <artifactId>parent-core</artifactId>
    <version>${revision}</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>neo4j-schema</artifactId>
  <name>Neo4j Schema</name>
  <description>Contains Neo4j @Node entities and repositories for ArDoCo.</description>

  <dependencyManagement />

  <dependencies>

    <dependency>
      <groupId>edu.stanford.nlp</groupId>
      <artifactId>stanford-corenlp</artifactId>
      <version>4.5.10</version>
    </dependency>

    <dependency>
      <groupId>io.github.ardoco.core</groupId>
      <artifactId>common</artifactId>
      <version>${revision}</version>
    </dependency>
    <dependency>
      <groupId>io.github.ardoco.core</groupId>
      <artifactId>pipeline-core</artifactId>
      <version>${revision}</version>
    </dependency>
    <dependency>
      <groupId>io.github.ardoco.id</groupId>
      <artifactId>pipeline-id</artifactId>
      <version>${revision}</version>
    </dependency>
    <dependency>
      <groupId>io.github.ardoco.tlr</groupId>
      <artifactId>pipeline-tlr</artifactId>
      <version>${revision}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-neo4j</artifactId>
    </dependency>
      <dependency>
          <groupId>org.projectlombok</groupId>
          <artifactId>lombok</artifactId>
          <scope>provided</scope>
      </dependency>
      <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-test</artifactId>
          <scope>test</scope>
      </dependency>
      <dependency>
          <groupId>org.testcontainers</groupId>
          <artifactId>junit-jupiter</artifactId>
      </dependency>

      <dependency>
          <groupId>org.testcontainers</groupId>
          <artifactId>neo4j</artifactId>
          <scope>test</scope>
      </dependency>

      <dependency>
          <groupId>org.testcontainers</groupId>
          <artifactId>testcontainers</artifactId>
      </dependency>
      <dependency>
          <groupId>org.neo4j.driver</groupId>
          <artifactId>neo4j-java-driver</artifactId>
      </dependency>
    </dependencies>
</project>
