name: Sonar Cloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sonarcloud:
    if: ${{ github.actor != 'dependabot[bot]' }} 
    uses: ardoco/actions/.github/workflows/sonarcloud.yml@main
    with:
      with-submodules: true
      runs-on: self-hosted
      install-self: true
      dependencies: "https://github.com/ArDoCo/InconsistencyDetection.git"
    secrets:
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}

